export enum REMINDER_ACTIONS {
    GET_REMINDER,
    GET_REMINDER_SUCCESS,
    GET_REMINDER_ERROR,

    ADD_REMINDER,
    ADD_REMINDER_SUCCESS,
    ADD_REMINDER_ERROR,

    UPDATE_REMINDER,
    UPDATE_REMINDER_SUCCESS,
    UPDATE_REMINDER_ERROR,

    DELETE_REMINDER,
    DELETE_REMINDER_SUCCESS,
    DELETE_REMINDER_ERROR
}
